from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('admins/', views.home, name='home'),
    path('accounts/', views.account_list, name='account_list'),
    path('article_list/', views.article_list, name='article_list'),
    path('pending_articles/', views.pending_articles, name='pending_articles'),
    path("approve_article/<int:article_id>/", views.approve_article, name="approve_article"),
    path('base/', views.base, name='base'),
    path('login/', views.login_auth, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('add_article/', views.add_article, name='add_article'),
    path('edit/<int:article_id>/', views.edit_article, name='edit_article'),
    path('delete_article/<int:article_id>/', views.delete_article, name='delete_article'),
    path('add_user/', views.add_user, name='add_user'),
    path('edit_user/<int:user_id>', views.edit_user, name='edit_user'),
    path("delete_user/<int:user_id>/", views.delete_user, name="delete_user"),
    path('activities/', views.activities, name='activities'),
    path('activities/<int:pk>/', views.activity_detail, name='activity_detail'),
    path('activities/ajax/', views.past_activities_ajax, name='past_activities_ajax'),
    path('about_us/', views.about_us, name='about_us'),
    path('uga/', views.uga, name='uga'),
    path('research/', views.research, name='research'),
    path('gender_clubs/', views.gender_clubs, name='gender_clubs'),
    path('approve_research/<int:research_id>/', views.approve_research, name='approve_research'),
    path('research_list/',views.research_list, name='research_list'),
    path('research/<int:pk>/', views.research_detail, name='research_detail'),
    path('research_list/add',views.add_research, name='add_research'),
    path('pending_research/',views.pending_research, name='pending_research'),
    path('edit_research/<int:research_id>/', views.edit_research, name='edit_research'),
    path('delete_research/<int:pk>/', views.delete_research, name='delete_research'),
    path('featured-research/', views.feature_research, name='feature_research'),
    path('add-category/', views.add_category, name='add_category'),
    path('hero/', views.hero_section, name='hero_section'),
    path('hero/update/', views.update_hero_section, name='update_hero_section'),
    path('admins/mission_vision/', views.mission_vision_info, name='mission_vision_info'),
    path('admins/mission_vision/update/', views.update_mission_vision, name='update_mission_vision'),
    path('key-objectives/', views.key_objectives_info, name='key_objectives_info'),
    path('key-objectives/update/', views.update_key_objectives, name='update_key_objectives'),
    path('edit-banner/', views.edit_banner, name='edit_banner'),
    path('manage-cards/', views.manage_cards, name='manage_cards'),
    path('edit-card/<int:card_id>/', views.edit_card, name='edit_card'),
    path('create-card/', views.create_card, name='create_card'),
    path('delete-card/<int:card_id>/', views.delete_card, name='delete_card'),
    path('team/', views.team_list, name='team_list'),
    path('team/create/', views.team_create, name='team_create'),
    path('team/edit/<int:pk>/', views.team_edit, name='team_edit'),
    path('team/delete/<int:pk>/', views.team_delete, name='team_delete'),
    path('themes/', views.theme_settings, name='theme_settings'),
    path('themes/<int:theme_id>/edit/', views.edit_theme, name='edit_theme'),
    path('themes/<int:theme_id>/delete/', views.delete_theme, name='delete_theme'),
    path('themes/<int:theme_id>/activate/', views.activate_theme, name='activate_theme'),
    path('footer/edit/', views.footer_info, name='footer_info'),
    path('footer/update/', views.update_footer_info, name='update_footer_info'),
    path('footer-info/', views.footer_info, name='footer_info'),
    path('update-footer-info/', views.update_footer_info, name='update_footer_info'),
    path('footer/', views.footer_info, name='footer_info'),
    path('footer/update/', views.update_footer_info, name='update_footer_info'),
    path('css/theme.css', views.theme_css, name='theme_css'),
    path('manage-carousel/', views.manage_carousel, name='manage_carousel'),
    path('add-carousel-image/', views.add_carousel_image, name='add_carousel_image'),
    path('update-carousel-image/<int:image_id>/', views.update_carousel_image, name='update_carousel_image'),
    path('delete-carousel-image/<int:image_id>/', views.delete_carousel_image, name='delete_carousel_image'),

    # Activities Carousel Management
    path('manage-activities-carousel/', views.manage_activities_carousel, name='manage_activities_carousel'),
    path('add-activities-carousel-image/', views.add_activities_carousel_image, name='add_activities_carousel_image'),
    path('update-activities-carousel-image/<int:image_id>/', views.update_activities_carousel_image, name='update_activities_carousel_image'),
    path('delete-activities-carousel-image/<int:image_id>/', views.delete_activities_carousel_image, name='delete_activities_carousel_image'),

    # About Us Carousel Management
    path('manage-aboutus-carousel/', views.manage_aboutus_carousel, name='manage_aboutus_carousel'),
    path('add-aboutus-carousel-image/', views.add_aboutus_carousel_image, name='add_aboutus_carousel_image'),
    path('update-aboutus-carousel-image/<int:image_id>/', views.update_aboutus_carousel_image, name='update_aboutus_carousel_image'),
    path('delete-aboutus-carousel-image/<int:image_id>/', views.delete_aboutus_carousel_image, name='delete_aboutus_carousel_image'),

    # UGA Carousel Management
    path('manage-uga-carousel/', views.manage_uga_carousel, name='manage_uga_carousel'),
    path('add-uga-carousel-image/', views.add_uga_carousel_image, name='add_uga_carousel_image'),
    path('update-uga-carousel-image/<int:image_id>/', views.update_uga_carousel_image, name='update_uga_carousel_image'),
    path('delete-uga-carousel-image/<int:image_id>/', views.delete_uga_carousel_image, name='delete_uga_carousel_image'),

    # Research Carousel Management
    path('manage-research-carousel/', views.manage_research_carousel, name='manage_research_carousel'),
    path('add-research-carousel-image/', views.add_research_carousel_image, name='add_research_carousel_image'),
    path('update-research-carousel-image/<int:image_id>/', views.update_research_carousel_image, name='update_research_carousel_image'),
    path('delete-research-carousel-image/<int:image_id>/', views.delete_research_carousel_image, name='delete_research_carousel_image'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
