# Generated by Django 5.1.5 on 2025-04-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0002_research'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='box1_content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='box1_title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='box2_content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='box2_title',
        ),
    ]
