# Generated by Django 5.1.5 on 2025-04-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0003_remove_article_box1_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Featured Category',
                'verbose_name_plural': 'Featured Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='research',
            name='featured_categories',
            field=models.ManyToManyField(blank=True, related_name='research_articles', to='user_views.featuredcategory'),
        ),
    ]
