# Generated by Django 5.1.5 on 2025-04-14 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0004_featuredcategory_research_featured_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='featuredcategory',
            options={'ordering': ['category__name'], 'verbose_name': 'Featured Category', 'verbose_name_plural': 'Featured Categories'},
        ),
        migrations.RemoveField(
            model_name='featuredcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='featuredcategory',
            name='name',
        ),
        migrations.AddField(
            model_name='featuredcategory',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_views.category'),
        ),
    ]
