# Generated by Django 5.1.5 on 2025-04-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0005_category_alter_featuredcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='research',
            name='featured_categories',
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ['-is_featured', 'featured_order', '-created_at'], 'verbose_name': 'Research', 'verbose_name_plural': 'Research'},
        ),
        migrations.AddField(
            model_name='research',
            name='featured_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='research',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='FeaturedCategory',
        ),
    ]
