# Generated by Django 5.1.5 on 2025-04-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0007_researchcategory_research_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='grrc@wmsu.edu.ph', max_length=254)),
                ('phone', models.CharField(default='(+63) 123-4567', max_length=20)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
