# Generated by Django 5.1.5 on 2025-04-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0008_footerinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerinfo',
            old_name='email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='footerinfo',
            old_name='phone',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='footerinfo',
            old_name='facebook_url',
            new_name='social_facebook',
        ),
        migrations.RenameField(
            model_name='footerinfo',
            old_name='instagram_url',
            new_name='social_instagram',
        ),
        migrations.RemoveField(
            model_name='footerinfo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='footer_logos/'),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='quick_link_about',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='quick_link_activities',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='footerinfo',
            name='quick_link_research',
            field=models.URLField(default='#'),
        ),
    ]
