# Generated by Django 5.1.5 on 2025-04-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0009_rename_email_footerinfo_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line_1', models.CharField(max_length=255)),
                ('title_line_2', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('visit_us_link', models.URLField()),
                ('logo_image', models.ImageField(upload_to='hero/')),
                ('background_image_mobile', models.ImageField(upload_to='hero/backgrounds/')),
                ('background_image_desktop', models.ImageField(upload_to='hero/backgrounds/')),
                ('learn_more_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='footerinfo',
            name='quick_link_about',
        ),
        migrations.RemoveField(
            model_name='footerinfo',
            name='quick_link_activities',
        ),
        migrations.RemoveField(
            model_name='footerinfo',
            name='quick_link_research',
        ),
    ]
