# Generated by Django 5.1.5 on 2025-04-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0010_herosection_remove_footerinfo_quick_link_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_title', models.CharField(default='Mission', max_length=255)),
                ('mission_description', models.TextField()),
                ('vision_title', models.CharField(default='Vision', max_length=255)),
                ('vision_description', models.TextField()),
                ('background_image_mobile', models.ImageField(upload_to='mission_vision/backgrounds/')),
                ('background_image_desktop', models.ImageField(upload_to='mission_vision/backgrounds/')),
            ],
        ),
    ]
