# Generated by Django 5.1.5 on 2025-04-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0011_missionvision'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionvision',
            name='mission_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missionvision',
            name='vision_points',
            field=models.TextField(blank=True, null=True),
        ),
    ]
