# Generated by Django 5.1.5 on 2025-04-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0012_missionvision_mission_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyObjectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
