# Generated by Django 5.1.5 on 2025-04-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0013_keyobjectives'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyObjectives',
        ),
    ]
