# Generated by Django 5.1.5 on 2025-04-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0014_delete_keyobjectives'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyObjectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Key Objectives', max_length=255)),
                ('intro', models.TextField()),
                ('objective_1_title', models.CharField(max_length=255)),
                ('objective_1_text', models.TextField()),
                ('objective_2_title', models.CharField(max_length=255)),
                ('objective_2_text', models.TextField()),
                ('objective_3_title', models.CharField(max_length=255)),
                ('objective_3_text', models.TextField()),
                ('objective_4_title', models.CharField(max_length=255)),
                ('objective_4_text', models.TextField()),
            ],
        ),
    ]
