# Generated by Django 5.1.5 on 2025-04-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0015_keyobjectives'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_image', models.ImageField(upload_to='banner/')),
                ('large_image', models.ImageField(upload_to='banner/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
