# Generated by Django 5.1.5 on 2025-04-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0016_dynamicbannerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cards/')),
                ('bg_color', models.CharField(default='#FEF8F8', max_length=20)),
                ('header_bg_color', models.CharField(default='#F196E5', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
