# Generated by Django 5.1.5 on 2025-04-29 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0017_contentcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcard',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='contentcard',
            name='header_bg_color',
        ),
    ]
