# Generated by Django 5.1.5 on 2025-04-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0018_remove_contentcard_bg_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='team_members/')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
