# Generated by Django 5.1.5 on 2025-04-30 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0019_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField()),
                ('primary_button', models.CharField(max_length=100)),
                ('primary_url', models.URLField()),
                ('secondary_button', models.CharField(max_length=100)),
                ('secondary_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UGAHeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField()),
                ('background_image', models.ImageField(upload_to='hero_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UGAImplementationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UGAKeyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UGAOverviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UGAOverviewCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_views.ugaoverviewsection')),
            ],
        ),
    ]
