# Generated by Django 5.1.5 on 2025-04-30 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0020_calltoaction_ugaherosection_ugaimplementationstep_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallToAction',
            new_name='UGACallToAction',
        ),
    ]
