# Generated by Django 3.2.25 on 2025-05-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0021_rename_calltoaction_ugacalltoaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herosection',
            old_name='background_image_desktop',
            new_name='background_image',
        ),
        migrations.RenameField(
            model_name='missionvision',
            old_name='background_image_desktop',
            new_name='background_image',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='background_image_mobile',
        ),
        migrations.RemoveField(
            model_name='missionvision',
            name='background_image_mobile',
        ),
    ]
