# Generated by Django 3.2.25 on 2025-05-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0022_auto_20250509_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicbannerimage',
            old_name='large_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='dynamicbannerimage',
            name='small_image',
        ),
    ]
