# Generated by Django 5.2.1 on 2025-05-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0024_themesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('quick_links', 'Quick Links'), ('resources', 'Resources'), ('other', 'Other')], default='other', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='footerinfo',
            options={'verbose_name': 'Footer Information', 'verbose_name_plural': 'Footer Information'},
        ),
    ]
