# Generated by Django 5.2.1 on 2025-05-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0025_footer_footerlink_alter_footerinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line_1', models.CharField(max_length=200)),
                ('title_line_2', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='hero/backgrounds/')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='hero/logos/')),
                ('link_url', models.URLField(blank=True, null=True)),
                ('link_text', models.CharField(default='Learn More', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
