# Generated by Django 5.2.1 on 2025-05-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0026_heroslide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSlide',
        ),
    ]
