# Generated by Django 5.1.6 on 2025-05-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0027_delete_heroslide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentcard',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterField(
            model_name='contentcard',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Cards are displayed in ascending order (1, 2, 3...)'),
        ),
    ]
