# Generated by Django 4.2.21 on 2025-05-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0028_alter_contentcard_options_alter_contentcard_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A title to help identify this image in the admin panel', max_length=255)),
                ('image', models.ImageField(upload_to='carousel/')),
                ('order', models.IntegerField(default=0, help_text='Order in which the image appears in the carousel')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
