# Generated by Django 4.2.21 on 2025-05-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0029_carouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionvision',
            name='background_image',
            field=models.ImageField(help_text='Upload a high-resolution image that will work responsively across all devices', upload_to='mission_vision/backgrounds/'),
        ),
    ]
