# Generated by Django 4.2.21 on 2025-05-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0030_alter_missionvision_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities_carousel/')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activities Carousel Image',
                'verbose_name_plural': 'Activities Carousel Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='missionvision',
            name='background_image',
            field=models.ImageField(upload_to='mission_vision/backgrounds/'),
        ),
    ]
