# Generated by Django 3.2.25 on 2025-05-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_views', '0032_aboutuscarousel_researchcarousel_ugacarousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
